// frontend/src/components/ios/IToast.vue
<script setup lang="ts">
import { AlertTriangle, CheckCircle2, AlertCircle, Info, X } from 'lucide-vue-next'
import { toastQueue, dismissToast } from '../../utils/toast'

// IToast ── v1.5.0 iOS 顶部下滑通知
// 设计：
//   - 屏幕顶部下滑（不是底部），离活动 cursor 远些
//   - 22px 大圆角 + glass blur (iOS 通知中心风)
//   - 4 种 tone：success/绿、error/红、warning/黄、info/蓝
//   - 多 toast 堆叠时 stagger 入场 + Transition Group move
//   - 点击 toast 任意位置可手动关闭（移动端常见手势）
//   - 自动 dismiss 由 utils/toast.ts 控制（默认 3s）

const handleDismiss = (id: number) => {
  dismissToast(id)
}
</script>

<template>
  <Teleport to="body">
    <div
      class="fixed top-[58px] left-1/2 z-[200] flex -translate-x-1/2 flex-col gap-2 pointer-events-none w-[min(460px,calc(100vw-2rem))]"
      aria-live="polite"
    >
      <TransitionGroup
        enter-active-class="transition duration-[280ms] ease-[cubic-bezier(0.34,1.56,0.64,1)]"
        enter-from-class="opacity-0 -translate-y-8 scale-95"
        enter-to-class="opacity-100 translate-y-0 scale-100"
        leave-active-class="transition duration-200 ease-in absolute left-0 right-0"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 -translate-y-3 scale-95"
        move-class="transition-all duration-300 ease-out"
      >
        <div
          v-for="t in toastQueue"
          :key="t.id"
          class="pointer-events-auto group flex items-start gap-3 rounded-[22px] border-2 px-4 py-3 shadow-[0_12px_36px_rgba(0,0,0,0.12)] dark:shadow-[0_12px_36px_rgba(0,0,0,0.4)] backdrop-blur-[24px] text-[14px] leading-snug cursor-pointer transition-transform hover:scale-[1.01]"
          :class="[
            t.kind === 'success'
              ? 'bg-emerald-50/95 dark:bg-emerald-950/70 border-emerald-500/25 text-emerald-800 dark:text-emerald-200'
              : t.kind === 'error'
                ? 'bg-rose-50/95 dark:bg-rose-950/70 border-rose-500/25 text-rose-800 dark:text-rose-200'
                : t.kind === 'warning'
                  ? 'bg-amber-50/95 dark:bg-amber-950/70 border-amber-500/25 text-amber-800 dark:text-amber-200'
                  : 'bg-white/95 dark:bg-[#1c1c1e]/95 border-black/[0.08] dark:border-white/[0.1] text-ios-text dark:text-ios-textDark',
          ]"
          @click="handleDismiss(t.id)"
        >
          <div class="shrink-0 pt-0.5">
            <CheckCircle2
              v-if="t.kind === 'success'"
              class="w-[22px] h-[22px] text-emerald-500"
              stroke-width="2.4"
            />
            <AlertCircle
              v-else-if="t.kind === 'error'"
              class="w-[22px] h-[22px] text-rose-500"
              stroke-width="2.4"
            />
            <AlertTriangle
              v-else-if="t.kind === 'warning'"
              class="w-[22px] h-[22px] text-amber-500"
              stroke-width="2.4"
            />
            <Info v-else class="w-[22px] h-[22px] text-ios-blue" stroke-width="2.4" />
          </div>
          <p class="flex-1 whitespace-pre-line break-words font-semibold">{{ t.message }}</p>
          <button
            type="button"
            class="shrink-0 -mr-1 -mt-1 opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded-full hover:bg-black/[0.06] dark:hover:bg-white/[0.08]"
            @click.stop="handleDismiss(t.id)"
            aria-label="关闭"
          >
            <X class="w-3.5 h-3.5" stroke-width="2.5" />
          </button>
        </div>
      </TransitionGroup>
    </div>
  </Teleport>
</template>

// frontend/src/components/ios/IToast.tsx
import { CheckCircle2, XCircle, Info, AlertTriangle, X } from "lucide-react";
import { dismissToast, useToastQueue, type ToastKind } from "../../utils/toast";

const KIND_ICON: Record<ToastKind, typeof CheckCircle2> = {
  success: CheckCircle2,
  error: XCircle,
  warning: AlertTriangle,
  info: Info,
};

const KIND_TONE: Record<ToastKind, string> = {
  success: "border-emerald-500/30 bg-emerald-500/[0.10] text-emerald-700 dark:text-emerald-300",
  error: "border-rose-500/30 bg-rose-500/[0.10] text-rose-700 dark:text-rose-300",
  warning: "border-amber-500/30 bg-amber-500/[0.10] text-amber-700 dark:text-amber-300",
  info: "border-ios-blue/30 bg-ios-blue/[0.10] text-ios-blue dark:text-blue-300",
};

/**
 * IToast — 全局轻提示。底部右侧堆叠列表 + 双击/X 关闭，按类型着色。
 */
export default function IToast() {
  const queue = useToastQueue();
  if (queue.length === 0) {
    return null;
  }
  return (
    <div className="fixed bottom-6 right-6 z-[120] flex flex-col gap-2 pointer-events-none">
      {queue.map((t) => {
        const Icon = KIND_ICON[t.kind];
        return (
          <div
            key={t.id}
            className={[
              "pointer-events-auto",
              "min-w-[260px] max-w-[420px] rounded-[14px] border px-4 py-2.5 backdrop-blur-md shadow-lg",
              "flex items-start gap-2.5 ios-page-enter whitespace-pre-line text-[13px] font-semibold",
              KIND_TONE[t.kind],
            ].join(" ")}
          >
            <Icon className="h-[18px] w-[18px] shrink-0 mt-0.5" strokeWidth={2.4} />
            <span className="flex-1 leading-relaxed">{t.message}</span>
            {t.action ? (
              <button
                type="button"
                className={[
                  "no-drag-region shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-bold transition-colors",
                  t.action.destructive
                    ? "border-rose-500/40 bg-rose-500/10 text-rose-700 hover:bg-rose-500/20 dark:text-rose-300"
                    : "border-current/30 bg-white/15 hover:bg-white/30",
                ].join(" ")}
                onClick={() => {
                  try {
                    t.action?.onClick();
                  } finally {
                    dismissToast(t.id);
                  }
                }}
              >
                {t.action.label}
              </button>
            ) : null}
            <button
              type="button"
              className="no-drag-region opacity-60 hover:opacity-100 transition-opacity"
              onClick={() => dismissToast(t.id)}
              aria-label="关闭"
            >
              <X className="h-3.5 w-3.5" strokeWidth={2.4} />
            </button>
          </div>
        );
      })}
    </div>
  );
}
